# Generated by Django 4.2.1 on 2023-05-14 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chat_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chat')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='Sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sender'),
        ),
    ]
