# Generated by Django 4.2.1 on 2023-05-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sender_alter_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sender',
            name='Chat',
        ),
    ]
